workflows:
  ios_build_unsigned:
    name: iOS Build (Unsigned with Fastlane)
    environment:
      xcode: latest
      cocoapods: default
      node: 16
      vars:
        FASTLANE_SKIP_UPDATE_CHECK: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Run Fastlane
        script: fastlane ios build_unsigned
    artifacts:
      - ios/build/*.ipa
